name: Build & Deploy
on:
  push:
    branches:
      - main
  pull-request:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
      - uses: actions/checkout@v2

      - name: Set up Go
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - run: go version

      - name: Go mod
      - run: |
          go env -w GO111MODULE=on
          go env -w GOPROXY=https://goproxy.io,direct
          go mod download

      - name: Run GoReleaser
          uses: goreleaser/goreleaser-action@v2
          with:
            version: latest
            args: release --rm-dist
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}