name: Release
on: [ push,pull_request ]

jobs:
  release:
    env:
      GO111MODULE: on
      GOPROXY: https://goproxy.io,direct
    strategy:
      matrix:
        go-version: [ ^1.15 ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: go version

      - name: Go mod download
        run: go mod download

      - name: Build
        run: |
          go build -ldflags "-s -w" -o jd_seckill

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}